// Generated by CoffeeScript 1.7.1
var auth, config, csup, googleapis;

csup = require('./csuplib');

googleapis = require("googleapis");

config = csup.checkConfig();

auth = new googleapis.OAuth2Client(config.clientID, config.clientSecret, config.redirectURL);

if (!config.clientID || !config.clientSecret) {
  console.error("There are no valid clientID and clientSecret set in `" + csup.configFile + "`, please complete values");
  process.exit(1);
}

console.log('** AUTH PROCESS **');

googleapis.discover("drive", "v2").execute(function(err, client) {
  var getAccessToken, url;
  url = auth.generateAuthUrl({
    scope: config.scope
  });
  getAccessToken = function(code) {
    return auth.getToken(code, function(err, tokens) {
      if (err) {
        console.error("Error while trying to retrieve access token", err);
        process.exit(1);
      }
      config.accessToken = tokens.access_token;
      config.tokenType = tokens.token_type;
      config.refreshToken = tokens.refresh_token;
      csup.storeConfig();
      console.log("Succesfully persisted access token");
      return process.exit(0);
    });
  };
  console.log("\n" + url);
  return csup.rl().question("\nVisit the url and enter the code here: ", getAccessToken);
});

//# sourceMappingURL=auth.map
