#!/usr/bin/env node

var argv = require('optimist').argv;
var csup = require('./csuplib');

if (argv._.indexOf('auth') >= 0) {

  require('./auth');

} else if ((argv._.indexOf('upload') >= 0)||(argv._.indexOf('up') >= 0)) {

  csup.config.filename = argv.n || argv.name || null;
  csup.config.type = argv.t || argv.type || null;

  require('./upload');

} else if ((argv._.indexOf('help') >= 0)||(argv.h || argv.help)) {

  console.log('csup v0.0.1 (cloud storage uploader), (c) 2014 by Philipp Staender')
  console.log("Usage: csup auth|upload|help -n --name $filename -t --type $contentType");

} else {

  console.error('Could not detect argument(s). Use -h or --help for more informations');

}
